#!/usr/bin/env bash

# Adapted from https://github.com/girst/hardpass-sendHID/blob/master/README.md

# Exit on first error.
set -e

# Treat undefined environment variables as errors.
set -u

modprobe libcomposite

cd /sys/kernel/config/usb_gadget/
mkdir -p g1
cd g1

echo 0x1d6b > idVendor  # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB2

# Configure the overall multi-gadget.
STRINGS_DIR="strings/0x409"
mkdir -p "$STRINGS_DIR"
echo "$(python3 -c 'import uuid; print(uuid.uuid4())')" > "${STRINGS_DIR}/serialnumber"
echo "DynaCo" > "${STRINGS_DIR}/manufacturer"
echo "Generic USB Keyboard and Mouse" > "${STRINGS_DIR}/product"

# Configure keyboard.
FUNCTIONS_DIR="functions/hid.usb0"
mkdir -p "$FUNCTIONS_DIR"
echo 1 > "${FUNCTIONS_DIR}/protocol" # Keyboard
echo 0 > "${FUNCTIONS_DIR}/subclass" # No subclass
echo 8 > "${FUNCTIONS_DIR}/report_length"

# Write the keyboard report descriptor
# Source: https://www.kernel.org/doc/html/latest/usb/gadget_hid.html
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > "${FUNCTIONS_DIR}/report_desc"

# Configure mouse.
MOUSE_FUNCTIONS_DIR="functions/hid.usb1"
mkdir -p "$MOUSE_FUNCTIONS_DIR"
echo 2 > "${MOUSE_FUNCTIONS_DIR}/protocol" # Mouse
echo 0 > "${MOUSE_FUNCTIONS_DIR}/subclass" # No subclass
echo 4 > "${MOUSE_FUNCTIONS_DIR}/report_length"

# Write the mouse report descriptor
# This descriptor defines a simple 3-button mouse (left, right, and middle)
echo -ne \\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x03\\x81\\x02\\x75\\x05\\x95\\x01\\x81\\x01\\x05\\x01\\x09\\x30\\x09\\x31\\x15\\x81\\x25\\x7f\\x75\\x08\\x95\\x02\\x81\\x06\\xc0\\xc0 > "${MOUSE_FUNCTIONS_DIR}/report_desc"

# Finish multi-gadget config.
CONFIG_INDEX=1
CONFIGS_DIR="configs/c.${CONFIG_INDEX}"
mkdir -p "$CONFIGS_DIR"
echo 120 > "${CONFIGS_DIR}/MaxPower"

CONFIGS_STRINGS_DIR="${CONFIGS_DIR}/strings/0x409"
mkdir -p "$CONFIGS_STRINGS_DIR"
echo "Config ${CONFIG_INDEX}: ECM network" > "${CONFIGS_STRINGS_DIR}/configuration"

# Link both HID functions to the configuration
ln -s "$FUNCTIONS_DIR" "${CONFIGS_DIR}/"
ln -s "$MOUSE_FUNCTIONS_DIR" "${CONFIGS_DIR}/"

# Set the UDC
ls /sys/class/udc > UDC

# Set permissions.
chmod 777 /dev/hidg0
chmod 777 /dev/hidg1
