#!/usr/bin/env bash

# Echo commands to stdout.
set -x

# Exit on first error.
set -e

# Treat undefined environment variables as errors.
set -u

SCRIPT_DIR="$(dirname "$(realpath "$BASH_SOURCE")")"

# Remove any existing dtoverlay=dwc2 lines in-case there are some weird edge-cases like "dtoverlay=dwc2,dr_mode=host"
# that will screw up our configuration.
sed -i '/dtoverlay=dwc2/d' /boot/firmware/config.txt

# Now prepend dtoverlay=dwc2 to the beginning of the file so it's not subsumed under a subsection, preventing it from being used.
echo -e "dtoverlay=dwc2\n$(cat /boot/firmware/config.txt)" > /boot/firmware/config.txt

if ! grep dwc2 /etc/modules; then
  echo "dwc2" >> /etc/modules
fi

ENABLE_RPI_HID_PATH=/opt/enable-rpi-hid
ENABLE_RPI_HID_DIR=$(dirname $ENABLE_RPI_HID_PATH)

mkdir -p "$ENABLE_RPI_HID_DIR"
cp ./enable-rpi-hid "$ENABLE_RPI_HID_PATH"
chmod +x "$ENABLE_RPI_HID_PATH"

cd $(mktemp -d)
sed -e "s@{{ key_mime_pi_initialize_hid_script_path }}@${ENABLE_RPI_HID_PATH}@g" \
  "$SCRIPT_DIR/usb-gadget.systemd.j2" > /lib/systemd/system/usb-gadget.service

systemctl daemon-reload
systemctl enable usb-gadget.service
